eitprocessing/binreader/event.py
eitprocessing/binreader/frameset.py
eitprocessing/binreader/phases.py
eitprocessing/binreader/reader.py
eitprocessing/binreader/sequence.py
eitprocessing/binreader/timing_error.py

This adds the copyright on top . Note (not yet linted)

adding top file explanations

---

.vscode/settings.json
eitprocessing/binreader/frameset.py
eitprocessing/binreader/sequence.py

Copied all the files from 
https://github.com/EIT-ALIVE/eitbinary/tree/main/eitbinary 
to 
https://github.com/EIT-ALIVE/eitprocessing/tree/main/eitprocessing/binreader
then checked what was missing from old repo as opposed to additions to new repo.
closes #17

re-add missing code from eitbinary repo

---

README.md

This updates to the new working documentation ()

update with docu link

---

.vscode/settings.json
eitprocessing/binreader/__init__.py
eitprocessing/binreader/frameset.py
eitprocessing/binreader/phases.py
eitprocessing/binreader/reader.py
eitprocessing/binreader/sequence.py
setup.cfg
tests/test_my_module.py
tests/test_timpel_sequence.py

I have added a class and methods for loading Timpel data, including the waveform data. 
Because the Sequence class was getting crowded with methods for different vendors, I created two child classes containing the vendor specific methods. 
I added tests for loading, partly loading, slicing and merging Timpel data.
fixes #26

feat: add class/methods for loading Timpel data

---

.github/next_steps/02_citation.md
.github/workflows/build.yml
.github/workflows/documentation.yml
.prospector.yml
CHANGELOG.md
CITATION.cff
README.dev.md
docs/developers.rst
docs/index.rst
project_setup.md

Compare this to the action name in #73
(VS Code automatically strips trailing spaces for me, so this was apparently updated as well....)
here:
in #73:
PS: Build is failing now, because the docker image was updated in #73
fixes #83

read python version and os in name of build action

---

eitprocessing/binreader/sequence.py

fix: do not raise warning if nframes is None

---

eitprocessing/filters/__init__.py
eitprocessing/filters/butterworth_filters.py
tests/test_butterworth_filter.py

This pull request introduces a class TimeDomainFilter, which is a superclass for the definition of time domain filters, as well as a set of Butterworth filters based on the TimeDomainFilter.
This pull request serves mainly as a proposal for the boilerplate for time domain filters.

feature: filter class definition

---

.vscode/settings.json
README.dev.md
eitprocessing/__init__.py
eitprocessing/binreader/__init__.py
eitprocessing/binreader/reader.py
eitprocessing/eit_data/event.py
eitprocessing/eit_data/phases.py
eitprocessing/plotting/plot.py
pyproject.toml
setup.cfg
tests/test_butterworth_filter.py
tests/test_sequence.py

This replaces the black formatter and prospector linter

style: use ruff for formatting and linting

---

eitprocessing/eit_data/__init__.py
eitprocessing/eit_data/draeger.py

Category field was missing in init . Added check for empty non eit data.

Hotfix medibus category wbaccinelli

---

.github/workflows/build.yml

ci: run ruff instead of prospector in the CI

---

eitprocessing/continuous_data/__init__.py

I added two suggestions for improvements of your improvements.

Slicedcopy continuousdata suggestions psomhorst

---

eitprocessing/continuous_data/__init__.py
eitprocessing/sequence/__init__.py

@psomhorst , was there a reason to remove `label` etc from `Sequence`? I re-added them now, because it's very useful to have it in the dashboard. I will also update the docstring and then open this PR for review, just wanted to check in already whether there was actually a reason to not want labels on Sequences.

Add labeling attributes to `Sequence`

---

eitprocessing/datahandling/loading/__init__.py

I guess this accidentally snuck into #166

fix: circular imports

---

eitprocessing/datahandling/continuousdata.py
eitprocessing/datahandling/eitdata.py
eitprocessing/datahandling/mixins/equality.py

When creating the new structure, we broke concatenation of EITData and ContinuousData. This is most apparent when loading multiple EIT files at once. This should fix that. 
I still expect we will create a common concatenation mixin at some point.

Fix concatenation

---

eitprocessing/datahandling/datacollection.py

DataCollection inherits from UserDict

---

eitprocessing/datahandling/continuousdata.py
eitprocessing/datahandling/datacollection.py
eitprocessing/datahandling/eitdata.py
eitprocessing/datahandling/mixins/slicing.py
eitprocessing/datahandling/sequence.py

This PR fixes #161.
I fixed the slicing issue by adding custom `select_by_time()` methods to DataCollection and Sequence.

Add time slicing to Sequence and DataCollection

---

docs/conf.py
eitprocessing/datahandling/loading/sentec.py

This keeps getting triggered by `ruff format`, so decided to finally do a hotfix for it :)

style: ruff formatting conf.py

---

eitprocessing/datahandling/intervaldata.py
eitprocessing/datahandling/sparsedata.py

ruff found a couple of missing spaces.

style: fix formatting errors

---

.github/workflows/dash_actions.yml
.github/workflows/documentation.yml
README.md

Update to the main readme with a short description, updated install instructions and a best practices badge.
Replaces #232.

docs: Update main readme

---

eitprocessing/features/breath_detection.py
tests/test_breath_detection.py

This allows find_breaths to accept either a ContinuousData object, or a Sequence object and a label pointing to a continuousdata object.

41c breaths detection singledispatch

---

eitprocessing/datahandling/continuousdata.py
eitprocessing/datahandling/eitdata.py
eitprocessing/datahandling/loading/__init__.py
eitprocessing/datahandling/loading/draeger.py
eitprocessing/datahandling/loading/sentec.py
eitprocessing/datahandling/loading/timpel.py
eitprocessing/datahandling/mixins/test_eq.ipynb
eitprocessing/parameters/eeli.py
eitprocessing/plotting/animate.py
notebooks/test_parameter_eeli_.ipynb
tests/mixins/test_eq.py
tests/mixins/test_slicing.py
tests/test_breath_detection.py
tests/test_eeli.py
tests/test_loading.py

Rename framerate to sample frequency

---

eitprocessing/datahandling/continuousdata.py
eitprocessing/datahandling/loading/draeger.py
eitprocessing/datahandling/loading/timpel.py
tests/test_breath_detection.py
tests/test_continuous_data.py
tests/test_eeli.py

Closes #209 
~Blocked by #290~

Add sample frequency attribute to ContinuousData

---

eitprocessing/datahandling/continuousdata.py
eitprocessing/datahandling/eitdata.py
eitprocessing/datahandling/intervaldata.py
eitprocessing/datahandling/sparsedata.py
tests/test_sparsedata.py

This PR adds length checks at initialisation of IntervalData, SparseData, ContinuousData and EITData.

Add length check to data collections

---

eitprocessing/datahandling/mixins/slicing.py

Add type hints to TimeIndexer

---

eitprocessing/datahandling/datacollection.py
eitprocessing/datahandling/loading/draeger.py
tests/conftest.py
tests/test_loading.py

Fix time axis wrapping

---

.github/workflows/release_github.yml

Update the token to PAT and set force_with_lease.

Update push actions

---

docs/api/plotting/pixelmap.md
docs/api/plotting/rate_detection.md
eitprocessing/plotting/rate_detection.py
mkdocs.yml

Adds existing plotting classes to documentation.

Add Plotting documentation

---

eitprocessing/datahandling/loading/__init__.py
eitprocessing/datahandling/mixins/equality.py
eitprocessing/datahandling/pixelmap.py
eitprocessing/features/pixel_breath.py
eitprocessing/features/rate_detection.py
eitprocessing/filters/mdn.py
eitprocessing/plotting/rate_detection.py
eitprocessing/roi/__init__.py
pyproject.toml
tests/mixins/test_slicing.py
tests/test_continuous_data.py
tests/test_eeli.py
tests/test_mdn_filter.py
tests/test_parameter_tiv.py
tests/test_pixel_breath.py

Updates to ruff 0.12.10 and fixes all issues resulting from the update.

Update ruff version
