EIT-ALIVE/eitprocessing

- .github/workflows/documentation.yml
- docs/conf.py
- eitprocessing/binreader/__init__.py
- setup.cfg
I had removed imports from the init in #33 to 'fix' linting issues, but this broke the notebook. I now recovered the imports and added an `__all__` to not tick off the linter.
closes #19 
alternative solution to #51
> fix notebook paths

- eitprocessing/binreader/sequence.py
- tests/test_sequence.py
setting the `vendor` argument of `Sequence` child class can no longer change the class.
I also added a comment regarding not using best practices (see #93 )
closes: #94
> fix: raise error for illegal vendor of  Sequence child

- eitprocessing/binreader/sequence.py
- tests/test_sequence.py
Allowed for `Sequence`s to have a `label` argument, which is intended as a human readable descriptor of the sequence.
If not provided, the object `id` is used instead (is this a good default?)
Slicing and merging methods allow for adding a new label, or auto-generate a descriptive label of the process performed.
closes #98
> feature add `label` as an argument to `Sequence`

- .vscode/settings.json
- eitprocessing/binreader/frameset.py
- eitprocessing/binreader/sequence.py
- tests/test_sequence.py
I guess it's technically both `docs` and `style` (and maybe a tiny bit `build`), which indicates that it's more than 1 thing and should theoretically be separate PRs, but it's all so minor that I can't really be bothered.
changes:
- remove obsolete importing of `List` and `Dict` from `typing` ([bfb2d8f](https://github.com/EIT-ALIVE/eitprocessing/pull/110/commits/bfb2d8fa1ef146e90bbec771787b4b7a025f274d))
- improve docstrings of `Sequence` ([c741aca](https://github.com/EIT-ALIVE/eitprocessing/pull/110/commits/c741acabeaf948a6a27d816f8d93e0c8f834a950))
- make `Vendor` docstring single line ([c741aca](https://github.com/EIT-ALIVE/eitprocessing/pull/110/commits/c741acabeaf948a6a27d816f8d93e0c8f834a950))
- add `vendor` argument to `Sequence.from_path` in notebooks …
> style: minor improvements to docstrings and type hints

- eitprocessing/continuous_data/__init__.py
- eitprocessing/continuous_data/continuous_data_collection.py
- eitprocessing/continuous_data/continuous_data_variant.py
- eitprocessing/eit_data/__init__.py
- eitprocessing/eit_data/eit_data_variant.py
- eitprocessing/eit_data/timpel.py
- eitprocessing/helper.py
- eitprocessing/mixins/equality.py
- eitprocessing/mixins/slicing.py
- eitprocessing/mixins/test_eq.ipynb
- eitprocessing/sequence/__init__.py
- eitprocessing/variants/__init__.py
- eitprocessing/variants/variant_collection.py
- tests/mixins/test_eq.py
This PR does the following:
- additions to docstring of slicing module (#132 ) + add init file to mixins subpackage
- create a generic `__eq__` function for alive data structures
- create a generic `isequivalent` function for alive data structures
- apply `isequivalent` throughout
> mixin class for equality and equivalence

- pyproject.toml
If `*args` or `**kwargs` are used for anything but passing arguments to another function, they probably should be named differently.
> Add ignore codes for ruff

- eitprocessing/continuous_data/__init__.py
- eitprocessing/eit_data/draeger.py
There were a few bugs with the `ContinuousData` class which meant that it was not initializable
- `_sliced_copy` is an abstract method of `SelectByTime`, but wasn't defined in `ContinuousData`, which inherits from it
- We defined this method now to allow using the class, but still need to check that it is defined correctly
- `_convert_medibus_data` wasn't using `time`, but was still using `loaded`
- `__set_attr__` was trying to read the attributes before they existed during initialization
- We now wrote is such that the check is skipped when initializing, but is executed when changing the attribute after initialization.
> fix: bug fixes on `ContinuousData` class

- eitprocessing/eit_data/draeger.py
I was working with EITData today and noticed loading Draeger data over network was terribly slow. We solved that problem earlier for SENTEC-data, but not yet for Draeger.
This simple addition using the mmap module speeds up data transfer drastically.
> Speed up loading Draeger data over network

- pyproject.toml
We have multiple objects that have an attribute called values. When addressing that attribute, Ruff assumes it's a pandas dataframe, triggering PD011 (https://docs.astral.sh/ruff/rules/pandas-use-of-dot-values/). 
I'd like to keep using values as the name for te attribute storing values.
> Add PD011 to ruff ignore list

- eitprocessing/datahandling/datacollection.py
- eitprocessing/datahandling/mixins/equality.py
- eitprocessing/datahandling/sequence.py
This bug fixes (?) the equality and equivalence checks for DataCollections introduced in #182.
Because the formal tests have not been entirely rewritten this is not extensively tested yet. Equivalence and equality were both tested ad hoc, as well as concatenation of two DataCollections.
Also adds concatenation of Sequence.continuous_data and Sequence.sparse_data (required for testing this). 
I propose merging this now to prevent bugs blocking usage of main.
> 178 datacollection from userdict wbaccinelli

- eitprocessing/datahandling/mixins/equality.py
- eitprocessing/datahandling/sequence.py
@DaniBodor I think this fixes the strange behaviour with `NotImplemented`. It was due to sparse_data becoming None when merging. Now it will become an empty DataCollection instead.
> 164b fix tests suggestion psomhorst

- README.dev.md
PRs #221, #225, and #226 were merged bypassing the requirement of review, as I needed to test a few things and it would have been tedious to request a review each time.
Together,these four PRs:
- fixed minor issues to allow easy releasing
- made a PyPi release
- updated the newest version to 1.0.1 (the patch version was to test something and then forgot to revert it)
- made adjustments to the release documentation
> docs: update info for making releases

- .github/workflows/build.yml
- .github/workflows/cffconvert.yml
- .github/workflows/dash_actions.yml
- .github/workflows/documentation.yml
- .github/workflows/lint.yml
This PR adds an action to trigger building of the dashboard from the current branch.
This PR should be reviewed in conjunction with [dashboard PR 47](https://github.com/EIT-ALIVE/eit_dash/pull/47)
For nomenclature, i will use _caller_ for the action in this repo and _callee_ for the action in the dashboard.
The following has been checked
additional minor changes:
- auto formatting yml files
- build actions use os and python versions as made explicit in matrix
closes #234
> ci: workflow to run the build of the dashboard

- .github/workflows/release.yml
Temporary change while working on PR Streamline release process #239.
While testing the action to make a GitHub release, I expect that we will be releasing on GitHub multiple times. We don't want each of these test releases to trigger a PyPi release.
When tests are finished, we can either delete all the GitHub test releases, or do a single new release to PyPi which bypasses all intermediate releases.
> ci: temporarily turn off PyPi release upon GitHub release

- .github/workflows/build.yml
- .github/workflows/cffconvert.yml
- .github/workflows/dash_actions.yml
- .github/workflows/lint.yml
- eitprocessing/datahandling/loading/draeger.py
- tests/conftest.py
- tests/test_loading.py
Closes #81 
I tested this by removing all data before a frame with an event from a BIN file.
> Add check for event on first frame

- .github/workflows/release_github.yml
- README.dev.md
- fix branch names to `main` and `develop` instead of `test_protected_XXX`
- forgot to do this in #242 
- use built-in branch reading system for GitHub actions (see [here](https://github.com/EIT-ALIVE/eitprocessing/actions/workflows/release_github.yml))
- this is mostly more convenient than the explicit one I wrote
- because the built-in one cannot be hidden, so would otherwise appear but have no function
- because the built-in one uses a drop-down menu (with search functionality) of existing branches rather than a string input for the one I wrote
- the downside is: the default cannot be changed to anything other than `main`, which should never actually be the release branch (the workflow will fail if main is set).
NB: I am also a bit confused now whether this PR should go to main or …
> ci: finalize github release action

- eitprocessing/datahandling/continuousdata.py
The function used by `derive` does not always require additional arguments, so it would be nice to make the `func_args` argument optional. See e.g. [here](https://github.com/EIT-ALIVE/eitprocessing/blob/demo_notebook_dbodor/notebooks/minidemo.ipynb)
> refactor: derive funcargs dbodor

- eitprocessing/datahandling/__init__.py
- eitprocessing/datahandling/continuousdata.py
- eitprocessing/datahandling/eitdata.py
- eitprocessing/datahandling/intervaldata.py
- eitprocessing/datahandling/sequence.py
- eitprocessing/datahandling/sparsedata.py
Closes #272.
In this implementation, the superclass is not very functional. It only inherits from Equivalence, removing the requirement therefore from the subclasses.
Ideally, the superclass would take define some common fields (attributes). However, any field (attribute) defined in the superclass would be first in de __init__ function. `label` and `name` have default values in `EITData`, which would not work with non-default fields like `path`. Also, `path` would no longer be the first argument, potentially breaking existing code. To move fields to`DataContainer`, they would have to be the first arguments, or we would have to switch to keyword-only arguments.
This PR also removes superfluous inheritance from Sequence.
> Add DataContainer superclass

- eitprocessing/categories.py
- eitprocessing/config/categories-compact.yaml
- pyproject.toml
- tests/test_categories.py
Closes #280 
This PR introduces a way to handle data categories. Data in containers can be labeled with a category string. Functions can check the category string of incoming data against a preset tree of categories.
> Add way to handle categories

- eitprocessing/datahandling/loading/__init__.py
Assuming that there will be future vendors for which we want to add loading methods, it makes some sense to raise a NotImplementedError here. This indicates (very subtly) to the user that we are planning/willing to add loading methods for it.
It is also in line with the docstring for the loading method.
If we decide to stick to the ValueError (which is equally reasonable), then the docstring should be changed instead to reflect this.
> refactor: update error when vendor does not exist

- .github/workflows/lint.yml
- pyproject.toml
ruff is in not yet mature and updated frequently, sometimes with large changes in linting rules. This often results in code changes in multiple unrelated files mid-PR. This PR fixes the ruff version both in the dev dependencies as the CI linting automation. Therefore, only manual changes to the ruff version will require linting fixes. 
I propose that before or after increasing the version number, someone can decide to increase the ruff version and fix all resulting linting errors, thus removing that responsibility from other developers.
> Limit ruff version to < 0.6

- pyproject.toml
Config data was not packaged with >= 1.4.0. This adds the categories config file to the distributed package.
> Add config data to package

- eitprocessing/datahandling/loading/__init__.py
- eitprocessing/datahandling/loading/draeger.py
- tests/conftest.py
- tests/mixins/test_eq.py
- tests/test_labels.py
- tests/test_loading.py
~~#192~~ #193 and #217 explain two limitation of loading Draeger data. This documents these.
> Document limitations for loading Draeger data

- eitprocessing/datahandling/loading/__init__.py
- eitprocessing/datahandling/loading/draeger.py
- tests/test_loading.py
Closes #217
In this PR, the sample frequency of Draeger data is estimated from the time axis in the data. If a sample frequency is provided during loading, this is used, but a difference between the estimated and provided frequency results in a warning. This unfortunately makes loading between manufacturers inconsistent, but we can work around that.
> Detect sample frequency for Draeger data

- .github/actions/install_eitprocessing/action.yml
- .github/workflows/release_github.yml
- .vscode/settings.json
- pyproject.toml
This PR was extensively tested in a separate repo. This workflow update cleans up the workflow and more clearly splits merging a PR from merging develop. The main improvement is explicitly closing a PR using the gh CLI.
This supports either creating a release from develop -> main or from a branch associated with a PR -> main. If you select a branch with no PR associated, the merge PR job will fail.
> Update Github draft release workflow

- eitprocessing/datahandling/__init__.py
- eitprocessing/datahandling/mixins/slicing.py
- eitprocessing/datahandling/sequence.py
- tests/test_sequence_data.py
This PR adds a data interface to sequences for easier access to data objects. Instead of `sequence.continuous_data['filtered impedance']` one can now use `sequence.data['filtered impedance']`. Adding data is also easier with `sequence.data.add(object)
Other dict function are also implemented, such that `sequence.data` can be used as a conglomeration of all data collections. 
This improves readability of end user code. The old interface is still intact and usable. To use the interface, all labels have to be unique across all data collections. 
Fixes #363
> Add data access object to sequences

- .github/actions/install_eitprocessing/action.yml
Apparently, we cached the entire python install directory, which lead to permission issues. We had to manually remove caches before to keep the workflow running. This update caches only the downloaded packages, which is not prone to the same permission issues.
> Update pip caching

- eitprocessing/datahandling/pixelmap.py
- eitprocessing/roi/__init__.py
- pyproject.toml
- tests/test_pixelmap.py
- tests/test_pixelmask.py
Adds a PixelMask class that allows masking any pixel data. This PR is aimed at the PixelMap PR #380, because it can be applied to PixelMask. I created a separate PR to separate review efforts/comments.
Also changes the `PixelMap.threshold` function to `create_mask_from_threshod()`.
> Add PixelMask class

- eitprocessing/filters/butterworth_filters.py
- tests/test_butterworth_filter.py
The Butterworth filters can't handle data with NaN-values. Currently, if you pass data with NaN-values to `apply_filter(...)`, it will silently return an array with all-NaN-data. This is difficult to debug.
This PR adds a check that raises an exception when the data to be filtered contains any NaN values. It also tips the user on how to fix the problem.
> Add exception when trying to filter data with NaN-values

- eitprocessing/plotting/filter.py
- pyproject.toml
Mkdocs dependencies get a minimum version. Also, the `mkdocs-jupyter` dependency is moved from the general group to the docs group.
As a testament to why this was necessary: apparently one module imported `dataclass` from `attrs` instead of `dataclasses`. This was not caught by tests partly because `attrs` was installed due to the `mkdocs-jupyter` dependency, and thus could be imported. This import is also fixed in this PR.
> Fix mkdocs dependencies

- .github/workflows/test_build_documentation.yml
Should close #428.
Deployment did not work due to permissions issues. This PR adds a personal access token to the checkout action, which sets up the permission properly, as tested in a separate repo. 
Also cleans up the action to reduce redundancy and clarify steps.
> Fix deployment of documentation
